runtime: python27
api_version: 1
threadsafe: yes

handlers:

# static content handlers
- url: /(img|css|fonts|js)/(.*)
  static_files: static/\1/\2
  upload: static/(img|css|fonts|js|svg)/(.*)

# dynamic handlers
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: "0.15"
